### ISSUE TITLE
jest resolve cannot find path in the test

### ISSUE THREAD

**Issue by aaftab** [ZiNai/check-email-exists#17]
Test suite failed to run
                                                                                                                                                              
    Cannot find module '../native' from 'index.js'

**Comment by ZiNai** [comment]
after **npm  install**,  **neon build** will generate **index.node** in native dir.
you can change the require as ```var addon = require("../native/index.node") ``` in the lib/index.js.
then run ```npm test```

Recently, I am working on a [new technology](https://napi.rs/), and I may develop a similar NPM package based on it. Maybe one day you can try a new one！



> Test suite failed to run
> 
> ```
> Cannot find module '../native' from 'index.js'
> ```
