### ISSUE TITLE
Support for Examples

### ISSUE THREAD

**Issue by vaibkamble** [ZiNai/check-email-exists#4]
Hi,

Can you please add one example to show how to use this? I have tried following the steps mentioned in Usage section in README but unable to get it working. 

Thanks,
Vaibhav

**Comment by ZiNai** [comment]
You can read the code from [the test folder](https://github.com/ZiNai/check-email-exists/blob/master/test/index.spec.js)
There only are tow functions : one is check email exists sync, another is async.
